# site settings
title: "0XFEDE"
subtitle: Federico Saldarini
email: youremailaddress@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Federico Saldarini
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/saldavonschwartz
linkedin_url: https://www.linkedin.com/in/federicosaldarini

# build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed
